<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>SasaLib.InventorAPI</RootNamespace>
    <AssemblyName>SasaLib.Inventor2025</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseVSHostingProcess>true</UseVSHostingProcess>
    <PlatformTarget>x64</PlatformTarget>
    <RegisterForComInterop>false</RegisterForComInterop>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <None Update="参考資料\既存のアドインをレジストリ フリーに変換する.docx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SasaLibTestFrame\SasaLib.DelegateWriteLine\SasaLib.DelegateWriteLine.csproj" />
    <ProjectReference Include="..\SasaLibDNet8\SasaLibDNet8.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="SasaLib.Inventor Version.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.VisualStudio.SDK.EmbedInteropTypes" Version="15.0.16" />
    <PackageReference Include="stdole" Version="7.0.3300" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Autodesk.iLogic.Interfaces">
      <HintPath>SDK\Autodesk.iLogic.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="Autodesk.Inventor.Interop">
      <HintPath>SDK\Autodesk.Inventor.Interop.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>