<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
		<Platforms>AnyCPU;x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>

	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib.Barcode\ImageUtilBarcode.cs" Link="ImageUtilBarcode.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Drawing.Common" Version="8.0.5" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SasaLibDNet8\SasaLibDNet8.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="BarcodeLib">
			<HintPath>..\..\SasaLibTestFrame\Barcode_src_1.0.0.21\BarcodeLib\bin\Release\BarcodeLib.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Import Project="..\SasaLibDNet8_AssemblyInfo\SasaLibDNet8_AssemblyInfo.projitems" Label="Shared" />

</Project>
