<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<Nullable>disable</Nullable>
		<DelaySign>false</DelaySign>
		<RootNamespace>InventorTOYOaddin</RootNamespace>
		<RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	</PropertyGroup>

	<ItemGroup>
    <ProjectReference Include="..\SasaLibDNet8\SasaLibDNet8.csproj" />
  </ItemGroup>

	<Import Project="..\SasaLibDNet8_AssemblyInfo\SasaLibDNet8_AssemblyInfo.projitems" Label="Shared" />

</Project>
