<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>

  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SasaLibDNet8\SasaLibDNet8.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MySql.Data">
      <HintPath>..\..\SasaLibTestFrame\SasaLib.MySQLConnect\Connector\mysql.data.dll</HintPath>
    </Reference>
    <Reference Include="SasaLibDelegateWriteLine">
      <HintPath>..\..\SasaLibTestFrame\SasaLibDelegateWriteLine\bin\Debug\SasaLibDelegateWriteLine.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
