<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
		<Platforms>AnyCPU;x64</Platforms>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
		<PlatformTarget>x64</PlatformTarget>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<PackAsTool>False</PackAsTool>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<RootNamespace>SasaLib</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\AssemblyDynamicLoad.cs" Link="AssemblyDynamicLoad.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\AsyncLock.cs" Link="AsyncLock.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Base32.cs" Link="Base32.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Base64.cs" Link="Base64.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\BinaryConvertTYPE.cs" Link="BinaryConvertTYPE.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\BinaryReaderExtensions.cs" Link="BinaryReaderExtensions.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\BinaryWriterExtensions.cs" Link="BinaryWriterExtensions.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\CallIntervalMonitor.cs" Link="CallIntervalMonitor.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\CharacterCode.cs" Link="CharacterCode.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ClsNetUse.cs" Link="ClsNetUse.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ClsWinError.cs" Link="ClsWinError.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Compress.cs" Link="Compress.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ConsoleOption.cs" Link="ConsoleOption.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ContorlValidate.cs" Link="ContorlValidate.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ControlExtensions.cs" Link="ControlExtensions.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\CreateTIFF.cs" Link="CreateTIFF.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Csv.cs" Link="Csv.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\CycleMeasurementMemory.cs" Link="CycleMeasurementMemory.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\DataGridViewUtil.cs" Link="DataGridViewUtil.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\DebugSupport.cs" Link="DebugSupport.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\DetectEncodingFromBOM.cs" Link="DetectEncodingFromBOM.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\DotNetFrameworkAppContextSetSwitch.cs" Link="DotNetFrameworkAppContextSetSwitch.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Encryption.cs" Link="Encryption.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\EncryptionAES.cs" Link="EncryptionAES.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Enviroment.cs" Link="Enviroment.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\EventsSummary.cs" Link="EventsSummary.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ExclusiveControl.cs" Link="ExclusiveControl.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\FileFolder.cs" Link="FileFolder.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\FileManager.cs" Link="FileManager.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\FindMissingAssemblyAndLoad.cs" Link="FindMissingAssemblyAndLoad.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\FormsControlUtil.cs" Link="FormsControlUtil.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\GetVersion.cs" Link="GetVersion.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\GUIDExtensions.cs" Link="GUIDExtensions.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ImageUtil.cs" Link="ImageUtil.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ImageUtil1.cs" Link="ImageUtil1.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\IPictureDispTool.cs" Link="IPictureDispTool.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Log.cs" Link="Log.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ManagedTemporaryFile.cs" Link="ManagedTemporaryFile.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ManagedTemporaryFolder.cs" Link="ManagedTemporaryFolder.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Math.cs" Link="Math.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\MemoryCheck.cs" Link="MemoryCheck.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Message.cs" Link="Message.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\MessageSend.cs" Link="MessageSend.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Network.cs" Link="Network.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ObjectConverter.cs" Link="ObjectConverter.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ObjectWithTypeJsonConverter.cs" Link="ObjectWithTypeJsonConverter.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\OScommand.cs" Link="OScommand.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\PipeLib.cs" Link="PipeLib.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\PrintConfig.cs" Link="PrintConfig.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\PrinterSimple.cs" Link="PrinterSimple.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\PrinterSimpleConfig.cs" Link="PrinterSimpleConfig.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\PrinterSimpleConfigData.cs" Link="PrinterSimpleConfigData.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\PrinterStatus.cs" Link="PrinterStatus.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Printing.cs" Link="Printing.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\ProcessControl.cs" Link="ProcessControl.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\RegAsm.cs" Link="RegAsm.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\REGutils.cs" Link="REGutils.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\SamplePrintingSetting.cs" Link="SamplePrintingSetting.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\SasaLibDoEvent.cs" Link="SasaLibDoEvent.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\SasaLibInfo.cs" Link="SasaLibInfo.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\SasaLibLogging.cs" Link="SasaLibLogging.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\SasaPJL.cs" Link="SasaPJL.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\Sound.cs" Link="Sound.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\SQL.cs" Link="SQL.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\StreamExtensions.cs" Link="StreamExtensions.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\StreamString.cs" Link="StreamString.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\StringBuffer.cs" Link="StringBuffer.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\StringParsing.cs" Link="StringParsing.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\StringUtil.cs" Link="StringUtil.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\TestPIPECLIENT.cs" Link="TestPIPECLIENT.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\TestPIPESERVER.cs" Link="TestPIPESERVER.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\TEST_RefRectionTool.cs" Link="TEST_RefRectionTool.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\TextFile.cs" Link="TextFile.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\TimeLib.cs" Link="TimeLib.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\UACUtils.cs" Link="UACUtils.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\WindowControl.cs" Link="WindowControl.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\WindowProcess.cs" Link="WindowProcess.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\WindowsExplorer.cs" Link="WindowsExplorer.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\WithFakeAccount.cs" Link="WithFakeAccount.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\XmlModify.cs" Link="XmlModify.cs" />
	  <Compile Include="..\..\SasaLibTestFrame\SasaLib\XmlSettingFile.cs" Link="XmlSettingFile.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="NeoSmart.AsyncLock" Version="3.2.1" />
		<PackageReference Include="runtime.native.System.IO.Compression" Version="4.3.2" />
		<PackageReference Include="stdole" Version="17.12.40391" />
		<PackageReference Include="System.Buffers" Version="4.6.0" />
		<PackageReference Include="System.Collections.Specialized" Version="4.3.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
		<PackageReference Include="System.Diagnostics.EventLog" Version="8.0.1" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.10" />
		<PackageReference Include="System.Drawing.Primitives" Version="4.3.0" />
		<PackageReference Include="System.IO.Compression" Version="4.3.0" />
		<PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
		<PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
		<PackageReference Include="System.IO.FileSystem.DriveInfo" Version="4.3.1" />
		<PackageReference Include="System.IO.FileSystem.Watcher" Version="4.3.0" />
		<PackageReference Include="System.IO.MemoryMappedFiles" Version="4.3.0" />
		<PackageReference Include="System.IO.Packaging" Version="9.0.0" />
		<PackageReference Include="System.IO.Pipes" Version="4.3.0" />
		<PackageReference Include="System.IO.UnmanagedMemoryStream" Version="4.3.0" />
		<PackageReference Include="System.Linq" Version="4.3.0" />
		<PackageReference Include="System.Management" Version="9.0.0" />
		<PackageReference Include="System.Memory" Version="4.6.0" />
		<PackageReference Include="System.ObjectModel" Version="4.3.0" />
		<PackageReference Include="System.Runtime.Extensions" Version="4.3.1" />
		<PackageReference Include="System.Runtime.Handles" Version="4.3.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
		<PackageReference Include="System.Threading" Version="4.3.0" />
		<PackageReference Include="System.Windows.Extensions" Version="9.0.0" />
		<PackageReference Include="Uno.UI" Version="5.5.66" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\SasaLibTestFrame\SasaLib.DelegateWriteLine\SasaLib.DelegateWriteLine.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Autodesk.Inventor.Interop">
		  <HintPath>..\SasaLibDNet8.Inventor2025\SDK\Autodesk.Inventor.Interop.dll</HintPath>
		</Reference>
		<Reference Include="Interop.IWshRuntimeLibrary">
		  <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Inventor 2022\Bin\interop.iwshruntimelibrary.dll</HintPath>
		</Reference>
	</ItemGroup>

	<Import Project="..\SasaLibDNet8_AssemblyInfo\SasaLibDNet8_AssemblyInfo.projitems" Label="Shared" />

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="&#xD;&#xA;  echo &quot;■ビルド後イベント実行&quot;&#xD;&#xA;&#xD;&#xA;  echo &quot;MSBuildProjectName= $(MSBuildProjectName)&#xD;&#xA;  echo &quot;AssemblyName= $(AssemblyName)&quot;&#xD;&#xA;  echo &quot;MSBuildProjectDirectory= $(MSBuildProjectDirectory)&quot;&#xD;&#xA;  echo &quot;MSBuildStartupDirectory= $(MSBuildStartupDirectory)&quot;&#xD;&#xA;  echo &quot;OutputPath = $(OutputPath )&quot;&#xD;&#xA;  echo &quot;FrameworkSDKRoot = $(FrameworkSDKRoot)&quot;&#xD;&#xA;  echo &quot;BaseIntermediateOutputPath= $(BaseIntermediateOutputPath)&quot;&#xD;&#xA;  echo &quot;OutDir = $(OutDir)&quot;&#xD;&#xA;  echo &quot;Configuration= $(Configuration)&quot;&#xD;&#xA;&#xD;&#xA;  echo &quot;■ビルド後イベント終了&quot;" />
	</Target>

</Project>
